version: 2
updates:
  # Version updates for Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      minor-bumps:
        update-types:
        - "minor"
        - "patch"
      
  # Version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
