[package]
name = "bodsky-archiver"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
tungstenite = { version ="0.24.0", features = ["rustls-tls-native-roots"] }
rustls = { version = "0.23.19" }
minicbor = "0.25.1"
