name: Continuous integration

on:
  pull_request:
  push:
    branches: main

env: 
  CARGO_TERM_COLOR: always
  # Disable incremental compilation for faster from-scratch builds
  CARGO_INCREMENTAL: 0
  # Remove debug info, which increases the size of target directory
  CARGO_PROFILE_TEST_DEBUG: 0


jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout directory
        uses: actions/checkout@v4
      
      - name: Setup Rust
        run: rustup toolchain install stable --no-self-update
        
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Cargo check
        run: cargo check --locked
      
      - name: Run tests
        run: cargo test --locked