name: Continuous integration

on:
  push:
    branches: main
    paths:
      - '**.rs'

env: 
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout directory
        uses: actions/checkout@v4
        
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Setup Rust
        run: rustup update stable && rustup default stable

      - name: Run cargo check
        run: cargo check

      - name: Run cargo clippy
        run: cargo clippy
      
      - name: Run cargo tests
        run: cargo test