name: Continuous integration

on:
  push:
    branches: main
  pull_request:
    paths:
      - '**.rs'

env: 
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    needs: check

  check:
    name: Cargo check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run cargo check
      - run: cargo check

      - name: Run cargo clippy
      - run: cargo clippy

      - name: Run cargo tests
      - run: cargo test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2

      - run: cargo fmt --all -- --check